[font]
size = 8.0

[font.normal]
family = "Monaspace Krypton NF"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
opacity = 0.9

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
